-- EB02 – Clash des Rebelles : impressions documentées d’après TCGdex.
-- Source : https://github.com/tcgdex/cards-database/tree/master/data/Sword%20%26%20Shield/Rebel%20Clash
-- Chaque numéro de collecteur correspond au fichier du même numéro dans la source.

DO $$
DECLARE
  v_set_id uuid;
  v_card_count integer;
  v_generic_count integer;
  v_owned_count integer;
BEGIN
  SELECT id INTO v_set_id
  FROM public.card_sets
  WHERE set_code = 'swsh2' AND language = 'FR';

  IF v_set_id IS NULL THEN
    RAISE EXCEPTION 'Série française swsh2 introuvable';
  END IF;

  SELECT count(*) INTO v_card_count
  FROM public.cards WHERE card_set_id = v_set_id;

  SELECT count(*) INTO v_generic_count
  FROM public.card_print_variants v
  JOIN public.cards c ON c.id = v.card_id
  WHERE c.card_set_id = v_set_id AND v.variant_key = 'catalog_base';

  SELECT count(*) INTO v_owned_count
  FROM public.card_print_variants v
  JOIN public.cards c ON c.id = v.card_id
  JOIN public.collection_cards cc ON cc.card_print_variant_id = v.id
  WHERE c.card_set_id = v_set_id AND v.variant_key = 'catalog_base';

  IF v_card_count <> 209 OR v_generic_count <> 209 THEN
    RAISE EXCEPTION 'État EB02 inattendu : % cartes, % variantes génériques', v_card_count, v_generic_count;
  END IF;

  IF v_owned_count <> 0 THEN
    RAISE EXCEPTION 'EB02 contient % exemplaires liés aux variantes génériques ; arrêt pour préserver la collection', v_owned_count;
  END IF;
END $$;

DELETE FROM public.card_print_variants v
USING public.cards c
WHERE c.id = v.card_id
  AND c.card_set_id = (SELECT id FROM public.card_sets WHERE set_code = 'swsh2' AND language = 'FR')
  AND v.variant_key = 'catalog_base';

INSERT INTO public.card_print_variants
  (card_id, variant_key, variant_label, finish_code, checklist_group, is_master_set_target)
SELECT
  c.id,
  desired.variant_key,
  desired.variant_label,
  desired.finish_code,
  'main',
  true
FROM (
  VALUES
  ('1','normal','Normale','normal'),
  ('1','reverse','Reverse','reverse'),
  ('2','normal','Normale','normal'),
  ('2','reverse','Reverse','reverse'),
  ('3','normal','Normale','normal'),
  ('3','holo','Holo','holo'),
  ('3','reverse','Reverse','reverse'),
  ('4','normal','Normale','normal'),
  ('4','reverse','Reverse','reverse'),
  ('5','normal','Normale','normal'),
  ('5','reverse','Reverse','reverse'),
  ('6','normal','Normale','normal'),
  ('6','reverse','Reverse','reverse'),
  ('7','normal','Normale','normal'),
  ('7','reverse','Reverse','reverse'),
  ('8','normal','Normale','normal'),
  ('8','reverse','Reverse','reverse'),
  ('9','normal','Normale','normal'),
  ('9','reverse','Reverse','reverse'),
  ('10','normal','Normale','normal'),
  ('10','reverse','Reverse','reverse'),
  ('11','normal','Normale','normal'),
  ('11','reverse','Reverse','reverse'),
  ('12','normal','Normale','normal'),
  ('12','reverse','Reverse','reverse'),
  ('13','normal','Normale','normal'),
  ('13','reverse','Reverse','reverse'),
  ('14','normal','Normale','normal'),
  ('14','reverse','Reverse','reverse'),
  ('15','normal','Normale','normal'),
  ('15','reverse','Reverse','reverse'),
  ('16','normal','Normale','normal'),
  ('16','reverse','Reverse','reverse'),
  ('17','holo','Holo','holo'),
  ('18','holo','Holo','holo'),
  ('19','holo','Holo','holo'),
  ('20','normal','Normale','normal'),
  ('20','reverse','Reverse','reverse'),
  ('21','normal','Normale','normal'),
  ('21','reverse','Reverse','reverse'),
  ('22','holo','Holo','holo'),
  ('22','holo','Holo','holo'),
  ('22','holo','Holo','holo'),
  ('22','reverse','Reverse','reverse'),
  ('23','holo','Holo','holo'),
  ('23','reverse','Reverse','reverse'),
  ('24','normal','Normale','normal'),
  ('24','reverse','Reverse','reverse'),
  ('25','normal','Normale','normal'),
  ('25','reverse','Reverse','reverse'),
  ('26','holo','Holo','holo'),
  ('27','normal','Normale','normal'),
  ('27','reverse','Reverse','reverse'),
  ('28','normal','Normale','normal'),
  ('28','reverse','Reverse','reverse'),
  ('29','normal','Normale','normal'),
  ('29','reverse','Reverse','reverse'),
  ('30','normal','Normale','normal'),
  ('30','reverse','Reverse','reverse'),
  ('31','normal','Normale','normal'),
  ('31','reverse','Reverse','reverse'),
  ('32','normal','Normale','normal'),
  ('32','reverse','Reverse','reverse'),
  ('33','holo','Holo','holo'),
  ('33','reverse','Reverse','reverse'),
  ('34','normal','Normale','normal'),
  ('34','reverse','Reverse','reverse'),
  ('35','holo','Holo','holo'),
  ('36','holo','Holo','holo'),
  ('37','normal','Normale','normal'),
  ('37','reverse','Reverse','reverse'),
  ('38','normal','Normale','normal'),
  ('38','reverse','Reverse','reverse'),
  ('39','normal','Normale','normal'),
  ('39','reverse','Reverse','reverse'),
  ('40','holo','Holo','holo'),
  ('40','reverse','Reverse','reverse'),
  ('41','normal','Normale','normal'),
  ('41','reverse','Reverse','reverse'),
  ('42','normal','Normale','normal'),
  ('42','reverse','Reverse','reverse'),
  ('43','holo','Holo','holo'),
  ('44','normal','Normale','normal'),
  ('44','reverse','Reverse','reverse'),
  ('45','normal','Normale','normal'),
  ('45','reverse','Reverse','reverse'),
  ('46','normal','Normale','normal'),
  ('46','reverse','Reverse','reverse'),
  ('47','normal','Normale','normal'),
  ('47','reverse','Reverse','reverse'),
  ('48','normal','Normale','normal'),
  ('48','reverse','Reverse','reverse'),
  ('49','holo','Holo','holo'),
  ('50','holo','Holo','holo'),
  ('51','normal','Normale','normal'),
  ('51','reverse','Reverse','reverse'),
  ('52','normal','Normale','normal'),
  ('52','reverse','Reverse','reverse'),
  ('53','normal','Normale','normal'),
  ('53','reverse','Reverse','reverse'),
  ('54','holo','Holo','holo'),
  ('54','holo','Holo','holo'),
  ('54','reverse','Reverse','reverse'),
  ('55','holo','Holo','holo'),
  ('55','holo','Holo','holo'),
  ('56','normal','Normale','normal'),
  ('56','reverse','Reverse','reverse'),
  ('57','normal','Normale','normal'),
  ('57','reverse','Reverse','reverse'),
  ('58','normal','Normale','normal'),
  ('58','reverse','Reverse','reverse'),
  ('59','normal','Normale','normal'),
  ('59','reverse','Reverse','reverse'),
  ('60','normal','Normale','normal'),
  ('60','reverse','Reverse','reverse'),
  ('61','normal','Normale','normal'),
  ('61','reverse','Reverse','reverse'),
  ('62','holo','Holo','holo'),
  ('62','reverse','Reverse','reverse'),
  ('63','normal','Normale','normal'),
  ('63','reverse','Reverse','reverse'),
  ('64','normal','Normale','normal'),
  ('64','reverse','Reverse','reverse'),
  ('65','normal','Normale','normal'),
  ('65','reverse','Reverse','reverse'),
  ('66','holo','Holo','holo'),
  ('66','reverse','Reverse','reverse'),
  ('67','holo','Holo','holo'),
  ('68','normal','Normale','normal'),
  ('68','reverse','Reverse','reverse'),
  ('69','normal','Normale','normal'),
  ('69','reverse','Reverse','reverse'),
  ('70','holo','Holo','holo'),
  ('70','holo','Holo','holo'),
  ('71','holo','Holo','holo'),
  ('72','holo','Holo','holo'),
  ('73','normal','Normale','normal'),
  ('73','reverse','Reverse','reverse'),
  ('74','normal','Normale','normal'),
  ('74','reverse','Reverse','reverse'),
  ('75','holo','Holo','holo'),
  ('75','reverse','Reverse','reverse'),
  ('76','normal','Normale','normal'),
  ('76','reverse','Reverse','reverse'),
  ('77','normal','Normale','normal'),
  ('77','reverse','Reverse','reverse'),
  ('78','normal','Normale','normal'),
  ('78','reverse','Reverse','reverse'),
  ('79','holo','Holo','holo'),
  ('79','reverse','Reverse','reverse'),
  ('80','normal','Normale','normal'),
  ('80','reverse','Reverse','reverse'),
  ('81','normal','Normale','normal'),
  ('81','reverse','Reverse','reverse'),
  ('82','normal','Normale','normal'),
  ('82','reverse','Reverse','reverse'),
  ('83','normal','Normale','normal'),
  ('83','reverse','Reverse','reverse'),
  ('84','normal','Normale','normal'),
  ('84','reverse','Reverse','reverse'),
  ('85','holo','Holo','holo'),
  ('85','reverse','Reverse','reverse'),
  ('86','normal','Normale','normal'),
  ('86','reverse','Reverse','reverse'),
  ('87','normal','Normale','normal'),
  ('87','reverse','Reverse','reverse'),
  ('88','normal','Normale','normal'),
  ('88','reverse','Reverse','reverse'),
  ('89','normal','Normale','normal'),
  ('89','reverse','Reverse','reverse'),
  ('90','normal','Normale','normal'),
  ('90','reverse','Reverse','reverse'),
  ('91','holo','Holo','holo'),
  ('91','holo','Holo','holo'),
  ('91','reverse','Reverse','reverse'),
  ('92','holo','Holo','holo'),
  ('93','holo','Holo','holo'),
  ('94','normal','Normale','normal'),
  ('94','reverse','Reverse','reverse'),
  ('95','holo','Holo','holo'),
  ('95','holo','Holo','holo'),
  ('95','reverse','Reverse','reverse'),
  ('96','normal','Normale','normal'),
  ('96','reverse','Reverse','reverse'),
  ('97','normal','Normale','normal'),
  ('97','reverse','Reverse','reverse'),
  ('98','normal','Normale','normal'),
  ('98','reverse','Reverse','reverse'),
  ('99','normal','Normale','normal'),
  ('99','reverse','Reverse','reverse'),
  ('100','normal','Normale','normal'),
  ('100','reverse','Reverse','reverse'),
  ('101','normal','Normale','normal'),
  ('101','reverse','Reverse','reverse'),
  ('102','normal','Normale','normal'),
  ('102','reverse','Reverse','reverse'),
  ('103','normal','Normale','normal'),
  ('103','reverse','Reverse','reverse'),
  ('104','normal','Normale','normal'),
  ('104','reverse','Reverse','reverse'),
  ('105','normal','Normale','normal'),
  ('105','reverse','Reverse','reverse'),
  ('106','normal','Normale','normal'),
  ('106','reverse','Reverse','reverse'),
  ('107','holo','Holo','holo'),
  ('107','reverse','Reverse','reverse'),
  ('108','holo','Holo','holo'),
  ('109','normal','Normale','normal'),
  ('109','reverse','Reverse','reverse'),
  ('110','holo','Holo','holo'),
  ('111','holo','Holo','holo'),
  ('111','reverse','Reverse','reverse'),
  ('112','normal','Normale','normal'),
  ('112','reverse','Reverse','reverse'),
  ('113','holo','Holo','holo'),
  ('113','reverse','Reverse','reverse'),
  ('114','normal','Normale','normal'),
  ('114','reverse','Reverse','reverse'),
  ('115','normal','Normale','normal'),
  ('115','reverse','Reverse','reverse'),
  ('116','normal','Normale','normal'),
  ('116','reverse','Reverse','reverse'),
  ('117','normal','Normale','normal'),
  ('117','reverse','Reverse','reverse'),
  ('118','normal','Normale','normal'),
  ('118','reverse','Reverse','reverse'),
  ('119','normal','Normale','normal'),
  ('119','reverse','Reverse','reverse'),
  ('120','normal','Normale','normal'),
  ('120','reverse','Reverse','reverse'),
  ('121','holo','Holo','holo'),
  ('122','holo','Holo','holo'),
  ('123','normal','Normale','normal'),
  ('123','reverse','Reverse','reverse'),
  ('124','normal','Normale','normal'),
  ('124','reverse','Reverse','reverse'),
  ('125','holo','Holo','holo'),
  ('125','reverse','Reverse','reverse'),
  ('126','normal','Normale','normal'),
  ('126','reverse','Reverse','reverse'),
  ('127','normal','Normale','normal'),
  ('127','reverse','Reverse','reverse'),
  ('128','normal','Normale','normal'),
  ('128','reverse','Reverse','reverse'),
  ('129','normal','Normale','normal'),
  ('129','reverse','Reverse','reverse'),
  ('130','normal','Normale','normal'),
  ('130','reverse','Reverse','reverse'),
  ('131','normal','Normale','normal'),
  ('131','reverse','Reverse','reverse'),
  ('132','normal','Normale','normal'),
  ('132','reverse','Reverse','reverse'),
  ('133','normal','Normale','normal'),
  ('133','reverse','Reverse','reverse'),
  ('134','normal','Normale','normal'),
  ('134','reverse','Reverse','reverse'),
  ('135','normal','Normale','normal'),
  ('135','reverse','Reverse','reverse'),
  ('136','holo','Holo','holo'),
  ('137','holo','Holo','holo'),
  ('138','holo','Holo','holo'),
  ('138','reverse','Reverse','reverse'),
  ('139','normal','Normale','normal'),
  ('139','reverse','Reverse','reverse'),
  ('140','normal','Normale','normal'),
  ('140','reverse','Reverse','reverse'),
  ('141','normal','Normale','normal'),
  ('141','reverse','Reverse','reverse'),
  ('142','normal','Normale','normal'),
  ('142','reverse','Reverse','reverse'),
  ('143','normal','Normale','normal'),
  ('143','reverse','Reverse','reverse'),
  ('144','normal','Normale','normal'),
  ('144','reverse','Reverse','reverse'),
  ('145','normal','Normale','normal'),
  ('145','reverse','Reverse','reverse'),
  ('146','normal','Normale','normal'),
  ('146','reverse','Reverse','reverse'),
  ('147','normal','Normale','normal'),
  ('147','reverse','Reverse','reverse'),
  ('148','normal','Normale','normal'),
  ('148','reverse','Reverse','reverse'),
  ('149','normal','Normale','normal'),
  ('149','reverse','Reverse','reverse'),
  ('150','normal','Normale','normal'),
  ('150','reverse','Reverse','reverse'),
  ('151','normal','Normale','normal'),
  ('151','reverse','Reverse','reverse'),
  ('152','normal','Normale','normal'),
  ('152','reverse','Reverse','reverse'),
  ('153','holo','Holo','holo'),
  ('154','holo','Holo','holo'),
  ('154','holo','Holo','holo'),
  ('154','holo','Holo','holo'),
  ('154','reverse','Reverse','reverse'),
  ('155','normal','Normale','normal'),
  ('155','reverse','Reverse','reverse'),
  ('156','normal','Normale','normal'),
  ('156','reverse','Reverse','reverse'),
  ('157','normal','Normale','normal'),
  ('157','reverse','Reverse','reverse'),
  ('158','normal','Normale','normal'),
  ('158','reverse','Reverse','reverse'),
  ('159','normal','Normale','normal'),
  ('159','reverse','Reverse','reverse'),
  ('160','normal','Normale','normal'),
  ('160','reverse','Reverse','reverse'),
  ('161','normal','Normale','normal'),
  ('161','reverse','Reverse','reverse'),
  ('162','normal','Normale','normal'),
  ('162','reverse','Reverse','reverse'),
  ('163','normal','Normale','normal'),
  ('163','reverse','Reverse','reverse'),
  ('164','normal','Normale','normal'),
  ('164','reverse','Reverse','reverse'),
  ('165','normal','Normale','normal'),
  ('165','reverse','Reverse','reverse'),
  ('166','normal','Normale','normal'),
  ('166','reverse','Reverse','reverse'),
  ('167','normal','Normale','normal'),
  ('167','reverse','Reverse','reverse'),
  ('168','normal','Normale','normal'),
  ('168','reverse','Reverse','reverse'),
  ('169','normal','Normale','normal'),
  ('169','reverse','Reverse','reverse'),
  ('170','normal','Normale','normal'),
  ('170','reverse','Reverse','reverse'),
  ('171','normal','Normale','normal'),
  ('171','reverse','Reverse','reverse'),
  ('172','normal','Normale','normal'),
  ('172','reverse','Reverse','reverse'),
  ('173','normal','Normale','normal'),
  ('173','reverse','Reverse','reverse'),
  ('174','normal','Normale','normal'),
  ('174','reverse','Reverse','reverse'),
  ('174','reverse','Reverse','reverse'),
  ('175','holo','Holo','holo'),
  ('176','holo','Holo','holo'),
  ('177','holo','Holo','holo'),
  ('178','holo','Holo','holo'),
  ('179','holo','Holo','holo'),
  ('180','holo','Holo','holo'),
  ('181','holo','Holo','holo'),
  ('182','holo','Holo','holo'),
  ('183','holo','Holo','holo'),
  ('184','holo','Holo','holo'),
  ('185','holo','Holo','holo'),
  ('186','holo','Holo','holo'),
  ('187','holo','Holo','holo'),
  ('188','holo','Holo','holo'),
  ('189','holo','Holo','holo'),
  ('190','holo','Holo','holo'),
  ('191','holo','Holo','holo'),
  ('192','holo','Holo','holo'),
  ('193','holo','Holo','holo'),
  ('194','holo','Holo','holo'),
  ('195','holo','Holo','holo'),
  ('196','holo','Holo','holo'),
  ('197','holo','Holo','holo'),
  ('198','holo','Holo','holo'),
  ('199','holo','Holo','holo'),
  ('200','holo','Holo','holo'),
  ('201','holo','Holo','holo'),
  ('202','holo','Holo','holo'),
  ('203','holo','Holo','holo'),
  ('204','holo','Holo','holo'),
  ('205','holo','Holo','holo'),
  ('206','holo','Holo','holo'),
  ('207','holo','Holo','holo'),
  ('208','holo','Holo','holo'),
  ('209','holo','Holo','holo')
) AS desired(collector_number, variant_key, variant_label, finish_code)
JOIN public.cards c
  ON c.card_set_id = (SELECT id FROM public.card_sets WHERE set_code = 'swsh2' AND language = 'FR')
 AND c.collector_number = desired.collector_number
ON CONFLICT (card_id, variant_key) DO NOTHING;
